name: JIRA tickets transition for PR and Releases
description: Move JIRA tickets found in PR commits or release diff
branding:
  icon: move
  color: red
inputs:
  github-token:
    description: Your everyday GitHub token used for GitHub Actions
    required: true
  target-status:
    description: To which status the issues found in commits should transition to
    required: true
  is-pull-request:
    description: 'if true, other input parameters will be ignored and keys from commits associated with pull request will be retrieved and parsed for Jira keys'
    required: false
    default: false
  jira-base-url:
    description: URL of Jira instance
    required: true
  jira-api-token:
    description: Access Token for Authorization
    required: true
  jira-user-email:
    description: Email of the user for which Access Token was created for
    required: true
runs:
  using: "node12"
  main: "index.js"
